from datetime import datetime
from typing import Dict, List, Optional


from bson.objectid import ObjectId
from pydantic import BaseModel, Field


class GenerateResponse(BaseModel):
    response: str | None = Field(default=None, description="The text content generated by the LLM.")

class Request(BaseModel):
    user_prompt: str = Field(description="The user's prompt.")
    provider: str = Field(default='mock', description="The generative AI provider to use ('openai', 'google', 'mock').")

class Log(BaseModel):
    """
    Schema for a single log entry retrieved from the database. 
    """
    timestamp: datetime
    level: str
    message: str

    logger_name: str
    pathname: Optional[str]
    funcName: Optional[str]
    lineno: Optional[int]

class LogHistory(BaseModel):
    history: List[Log]

class PromptRecord(BaseModel):
    """Schema for a single prompt and response record."""
    id: Optional[int] = Field(default=None, description="Database ID (autoincrement)")
    timestamp: datetime
    provider: str
    user_prompt: str
    llm_response: str
    duration_ms: Optional[int] = Field(default=None, description="Time taken for generation in milliseconds")

class QueryResponse(BaseModel): # maybe big dict
    _id: Optional[ObjectId] = None
    id: Optional[str] = None
    title: Optional[str] = None
    article_abstract: Optional[str] = None
    keywords: Optional[List[str]] = None
    authors: Optional[List[str]] = None
    venue: Optional[List[str]] = None
    date: Optional[datetime] = None
    teams: Optional[List[str]] = None

    


    