from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field

# We do NOT import Provider here, keeping this file minimal and dependency-free.

class GenerateResponse(BaseModel):
    """The response model for the /generate endpoint."""
    response: str | None = Field(default=None, description="The text content generated by the LLM.")

class Request(BaseModel):
    """The request model for the /generate endpoint."""
    user_prompt: str = Field(description="The user's prompt or question.")
    # provider is intentionally defined as str here to avoid circular imports.
    provider: str = Field(default='mock', description="The generative AI provider to use ('openai', 'google', 'mock').")




class Log(BaseModel):
    """
    Schema for a single log entry retrieved from the database. 
    """
    timestamp: datetime
    level: str
    message: str
    
    # Technical metadata captured by the Python logging module
    logger_name: str
    pathname: Optional[str]
    funcName: Optional[str]
    lineno: Optional[int]

class LogHistory(BaseModel):
    history: List[Log]


# --- Prompt Record Schema (NEW) ---

class PromptRecord(BaseModel):
    """Schema for a single prompt and response record."""
    id: Optional[int] = Field(default=None, description="Database ID (autoincrement)")
    timestamp: datetime
    provider: str
    user_prompt: str
    llm_response: str
    duration_ms: Optional[int] = Field(default=None, description="Time taken for generation in milliseconds")
    